### ISSUE TITLE
Not reporting all errors on first run

### ISSUE THREAD

**Issue by mcristina422** [tetafro/godot#5]
I'm running this with golangci-lint on a project that has many godot errors. It is only reporting 3 failures and then I'll fix those failures and it will report more. I tried replicating this locally using the testdata and the build without golangci-lint and did not experience the same issue. 

Maybe there is some sort of limit when golangci-lint reports it? But other linters report more than 3 issues

`golangci-lint version 1.26.0`

**Comment by tetafro** [comment]
GolangCI Lint omits messages from one linter if they have same text. It can be configured ([see readme](https://github.com/golangci/golangci-lint/blob/master/README.md#command-line-options))
```
--max-same-issues int            Maximum count of issues with the same text. Set to 0 to disable (default 3)
```

AFAIK this is a global setting and cannot be set for one linter.

> But other linters report more than 3 issues

Most probably because messages are different
